name: aws_lambda_dart_docker
description: >-
  A template repository for running Dart container in AWS Lambda.
version: 0.0.1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  aws_lambda_dart_runtime: ^1.0.3+2

dev_dependencies:
  pedantic: ^1.9.0
